In [1]:
import pandas as pd
import numpy as np

In [3]:
pj3 = pd.read_csv(r'/Users/edgartome_1/IronHack/IronProjects/Project6/Payments_final.csv')

In [4]:
pj3

,Debtor,Creditor,Type,Reference,Initial Amount,Currency,Bank,Charges,Date,Time (local),Status,Rf_Am,Code,Country
0,Alpha Inc,ACME INVEST,fin.101,REF211,10000,USD,CHASUS3AXXX,0.020,2021-03-16,08:15:00,NEW,REF211 10000,US,USA
1,Alpha Inc,ACME INVEST,fin.101,REF211,10000,USD,BINAADADXXX,0.015,2021-03-17,15:45:00,COMPLETED,REF211 10000,AD,Andorra
2,Alpha Inc,ACME ONE CORP,fin.101,REFTEST01,4537,USD,CHASUS3AXXX,0.020,2021-03-16,00:00:00,NEW,REFTEST01 4537,US,USA
3,Alpha Inc,ACME ONE CORP,fin.101,REFTEST01,4537,USD,BINAADADXXX,0.010,2021-03-16,12:45:00,PENDING,REFTEST01 4537,AD,Andorra
4,Alpha Inc,ACME ONE CORP,fin.101,REFTEST01,4537,USD,BSJUARBJXXX,0.020,2021-03-18,14:15:00,COMPLETED,REFTEST01 4537,AR,Argentina
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,Alpha Inc,ALT 2 INC,fin.101,REFD202103,17430,USD,CHASUS3AXXX,0.020,2021-07-12,15:41:00,PENDING,REFD202103 17430,US,USA
86,Alpha Inc,ALT 2 INC,fin.101,REFD202103,17430,USD,CHASUS3AXXX,0.010,2021-07-13,18:10:00,DELIVERED,REFD202103 17430,US,USA
87,Alpha Inc,Beta Corp,fin.101,REF001,12000,USD,CHASUS3AXXX,0.010,2021-10-05,12:43:00,NEW,REF001 12000,US,USA
88,Alpha Inc,Beta Corp,fin.101,REF001,12000,USD,CHASUS3AXXX,0.020,2021-10-05,14:32:00,PENDING,REF001 12000,US,USA
89,Alpha Inc,Beta Corp,fin.101,REF001,12000,EUR,BINAADADXXX,0.010,2021-10-07,18:21:00,PENDING,REF001 12000,AD,Andorra

In [7]:
pd.crosstab([pj3['Rf_Am'], pj3['Status']],[pj3['Date']], margins=True, margins_name="Total")

Date                       2020-11-20  2020-11-21  2020-11-22  2020-11-27  \
Rf_Am           Status
REF001 12000    NEW                 0           0           0           0
                PENDING             0           0           0           0
REF001 3326     NEW                 0           0           0           0
                PENDING             0           0           0           0
REF001DEMO 1100 COMPLETED           0           0           0           0
...                               ...         ...         ...         ...
REFTEST01 4537  NEW                 0           0           0           0
                PENDING             0           0           0           0
REFZ999 12100   COMPLETED           0           0           0           0
                NEW                 0           0           0           0
Total                               3           2           1           2

Date                       2021-01-05  2021-01-13  2021-01-14  2021-01-15  \
Rf_Am           Status
REF001 12000    NEW                 0           0           0           0
                PENDING             0           0           0           0
REF001 3326     NEW                 0           0           0           0
                PENDING             0           0           0           0
REF001DEMO 1100 COMPLETED           0           0           0           0
...                               ...         ...         ...         ...
REFTEST01 4537  NEW                 0           0           0           0
                PENDING             0           0           0           0
REFZ999 12100   COMPLETED           0           0           0           0
                NEW                 0           0           0           0
Total                               3           4           2           4

Date                       2021-01-21  2021-01-22  ...  2021-11-03  \
Rf_Am           Status                             ...
REF001 12000    NEW                 0           0  ...           0
                PENDING             0           0  ...           0
REF001 3326     NEW                 0           0  ...           0
                PENDING             0           0  ...           0
REF001DEMO 1100 COMPLETED           0           0  ...           0
...                               ...         ...  ...         ...
REFTEST01 4537  NEW                 0           0  ...           0
                PENDING             0           0  ...           0
REFZ999 12100   COMPLETED           0           0  ...           0
                NEW                 0           0  ...           0
Total                               2           1  ...           2

Date                       2021-11-20  2021-11-21  2021-11-22  2021-11-24  \
Rf_Am           Status
REF001 12000    NEW                 0           0           0           0
                PENDING             0           0           0           0
REF001 3326     NEW                 0           0           0           0
                PENDING             0           0           0           0
REF001DEMO 1100 COMPLETED           0           0           0           0
...                               ...         ...         ...         ...
REFTEST01 4537  NEW                 0           0           0           0
                PENDING             0           0           0           0
REFZ999 12100   COMPLETED           0           0           0           0
                NEW                 0           0           0           0
Total                               1           1           1           1

Date                       2021-12-19  2021-12-20  2022-01-10  2022-01-11  \
Rf_Am           Status
REF001 12000    NEW                 0           0           0           0
                PENDING             0           0           0           0
REF001 3326     NEW                 0           0           1           0
                PENDING             0           0           0           2
REF001DEMO 1100 COMPLETED           0           0           0           0
...                               ...         ...         ...         ...
REFTEST01 4537  NEW                 0           0           0           0
                PENDING             0           0           0           0
REFZ999 12100   COMPLETED           0           0           0           0
                NEW                 0           0           0           0
Total                               1           2           1           2

Date                       Total
Rf_Am           Status
REF001 12000    NEW            1
                PENDING        2
REF001 3326     NEW            1
                PENDING        2
REF001DEMO 1100 COMPLETED      1
...                          ...
REFTEST01 4537  NEW            1
                PENDING        1
REFZ999 12100   COMPLETED      1
                NEW            1
Total                         90

[83 rows x 50 columns]

In [11]:
pivoted = pj3.pivot(index="Rf_Am", columns="Status", values="Date")

ValueError: Index contains duplicate entries, cannot reshape